export { default as Container } from './Container'
export { default as Memes } from './Memes'
export { default as Button }from './Button'
export { default as Footer } from './Footer'
export { default as NaviBar } from './NaviBar'
export { default as Separator} from './Separator'